CREATE TABLE Users (
userID INT NOT NULL PRIMARY KEY  IDENTITY(1, 1),
fio NVARCHAR(512) NOT NULL,
phone NVARCHAR(11) NOT NULL,
login NVARCHAR(100) NOT NULL,
password NVARCHAR(100) NOT NULL,
userTypeID INT NOT NULL REFERENCES UserTypes(userTypeID)
)
